### ISSUE TITLE
Continuous data normalization methods

### ISSUE THREAD

**Issue by lucas-bishop** [SchlossLab/mikropml#229]
In Articles > vignettes > preprocessing data > Continuous data: the documentation says that the default normalization methods is to use c("center", "scale"). When I clicked that link it took me to combine function (c) rather than descriptions of the normalization methods which is what I was expecting. Were those supposed to be linked?

**Comment by kelly-sovacool** [comment]
Thanks Lucas! That's because the tool we use to build the documentation website automatically recognizes functions and creates links to their documentation, even from other packages and base R. I removed use of the combine function. We reference `caret::preProcess()` after the next code chunk and note that interested readers can find more details about the method options there.
