### ISSUE TITLE
Providing case weights

### ISSUE THREAD

**Issue by funnell** [SchlossLab/mikropml#271]
Hello,

How would I provide a vector of weights to e.g. glmnet through run_ml?

Thanks!

**Comment by pschloss** [comment]
Thanks for the question - the `coef` function from `caret` (a dependency of `mikropml`) should get you what you want...

```
coef(otu_mini_bin_results_glmnet$trained_model$finalModel, otu_mini_bin_results_glmnet$trained_model$bestTune$lambda)
```

**Comment by funnell** [comment]
Hi @pschloss, thanks for the reply. I mean, how would I provide the `weights` argument to the glmnet function. I have unbalanced classes and I'm trying to account for that without down/up-sampling.
Thanks for your help!

**Comment by kelly-sovacool** [comment]
Hi @funnell, mikropml doesn't currently support that but we're looking to add support for that soon!

**Comment by kelly-sovacool** [comment]
We now forward extra arguments given to `run_ml()` along to `caret::train()`, which allows you to provide case weights to e.g. `glmnet` via the `weights` argument. Since the weights correspond to rows in the training set, you'll also need to set custom indices for the training set (i.e. perform the train/test split before `run_ml()` rather than let it do it for you). Here's an example where the weights are calculated as the proportion of each class in the dataset.

```r
library(dplyr)
case_weights_dat <- otu_mini_bin %>%
    count(dx) %>%
    mutate(p = n / sum(n)) %>%
    select(dx, p) %>% 
    right_join(otu_mini_bin, by = 'dx') %>%
    select(-starts_with("Otu")) %>% 
    mutate(in_train = sample(c(TRUE, FALSE), size = nrow(otu_mini_bin), 
                             replace = TRUE, prob = c(0.70, 0.30)),
           row_num = row_number()) %>% 
    filter(in_train)
head(case_weights_dat)
#>       dx    p in_train row_num
#> 1 cancer 0.49     TRUE       3
#> 2 cancer 0.49     TRUE       4
#> 3 cancer 0.49     TRUE       5
#> 4 cancer 0.49     TRUE       6
#> 5 cancer 0.49     TRUE       8
#> 6 cancer 0.49     TRUE       9
results_weighted <- run_ml(otu_mini_bin,
                  'glmnet',
                  outcome_colname = 'dx',
                  seed = 2019,
                  training_frac = case_weights_dat %>% pull(row_num),
                  weights = case_weights_dat %>% pull(p))
```

This is now covered in the intro vignette here: https://www.schlosslab.org/mikropml/articles/introduction.html#case-weights
