### ISSUE TITLE
Create Snakemake workflow

### ISSUE THREAD

**Issue by wclose** [SchlossLab/mikropml#37]
Create Snakefile, config file, and environments for running analysis.

**Comment by wclose** [comment]
Do this before #6

**Comment by kelly-sovacool** [comment]
I'm willing to pitch in to help @wclose

**Comment by kelly-sovacool** [comment]
When running models from Snakemake, instead of using the CLI in `main.R` it'll probably be best to use a simple R script e.g.:
```r
mikRopML::run_model(
  snakemake@params[["seed"]],
  snakemake@params[["model"]],
  snakemake@params[["data"]],
  snakemake@params[["hyperparams"]],
  snakemake@params[["outcome"]],
  snakemake@params[["permutation"]]
)
```

Then the Snakemake rule would use the `script` directive e.g.:
```python
rule run_model
    input:
        R="run_model_smk.R"
        csv=...
    output:
        csv=...
    params:
        seed=...
        model=...
        ...
    script:
        "{input.R}"
```

I tend to think maybe the Snakemake example should be a separate repo since it's more of an application of using the package, but not part of the package itself.

**Comment by kelly-sovacool** [comment]
I'll circle back to this once I resolve #46

**Comment by kelly-sovacool** [comment]
In progress on branch `snakemake`
